/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (LoginEntry.as).
 */

package com.hansel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class LoginEntryBase implements IExternalizable {

        public var _greeting:String;
        public var _isLoggedIn:Boolean;
        public var _logoutURL:String;
        public var _redirectURL:String;
        public var _timestamp:Number;

        public function set greeting(value:String):void {
            _greeting = value;
        }
        public function get greeting():String {
            return _greeting;
        }

        public function set isLoggedIn(value:Boolean):void {
            _isLoggedIn = value;
        }
        public function get isLoggedIn():Boolean {
            return _isLoggedIn;
        }

        public function set logoutURL(value:String):void {
            _logoutURL = value;
        }
        public function get logoutURL():String {
            return _logoutURL;
        }

        public function set redirectURL(value:String):void {
            _redirectURL = value;
        }
        public function get redirectURL():String {
            return _redirectURL;
        }

        public function set timestamp(value:Number):void {
            _timestamp = value;
        }
        public function get timestamp():Number {
            return _timestamp;
        }

        public function readExternal(input:IDataInput):void {
            _greeting = input.readObject() as String;
            _isLoggedIn = input.readObject() as Boolean;
            _logoutURL = input.readObject() as String;
            _redirectURL = input.readObject() as String;
            _timestamp = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_greeting);
            output.writeObject(_isLoggedIn);
            output.writeObject(_logoutURL);
            output.writeObject(_redirectURL);
            output.writeObject(_timestamp);
        }
    }
}