/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (UpdateEntry.as).
 */

package com.hansel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class UpdateEntryBase implements IExternalizable {

        public var _activeUsers:ListCollectionView;
        public var _chatUpdates:ListCollectionView;

        public function set activeUsers(value:ListCollectionView):void {
            _activeUsers = value;
        }
        public function get activeUsers():ListCollectionView {
            return _activeUsers;
        }

        public function set chatUpdates(value:ListCollectionView):void {
            _chatUpdates = value;
        }
        public function get chatUpdates():ListCollectionView {
            return _chatUpdates;
        }

        public function readExternal(input:IDataInput):void {
            _activeUsers = input.readObject() as ListCollectionView;
            _chatUpdates = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_activeUsers);
            output.writeObject(_chatUpdates);
        }
    }
}