/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.hansel {

    [Bindable]
    [RemoteClass(alias="com.hansel.UserEntry")]
    public class UserEntry extends UserEntryBase {
        public function get label():String {
            return _nickName;
        }    	
    }
}